# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_tSQcWuM8Bs5cruQj4deIEoAvbHUePN
"""

import numpy as np
from matplotlib import pyplot as plt 

# 1st argument --> numbers ranging from 0 to 9,
# 2nd argument, row = 2, col = 3
array = np.random.randint(10, size=(3, 3))
array=array*np.random.randint(10, size=(3, 3))
print(array)
print('\n')  
#ploting our canvas    
plt.plot(array)    
#display the graph    
plt.show()